spring:
  profiles:
    active: dev
  servlet:
    multipart:
      maxFileSize: 30MB

springdoc:
  group-configs:
    - group: '接口模块c'
      paths-to-match: '/**'
      packages-to-scan: com.example.library

# mybatis
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.library.**.pojo.entity
  #typeEnumsPackage: org.springblade.dashboard.entity.enums
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"不操作", 2:"用户输入ID",3:"数字型snowflake", 4:"全局唯一ID UUID", 5:"字符串型snowflake";
      id-type: assign_id
      #字段策略
      insert-strategy: not_null
      update-strategy: not_null
      where-strategy: not_null
      #驼峰下划线转换
      table-underline: true
      # 逻辑删除配置
      # 逻辑删除全局值（1表示已删除，这也是Mybatis Plus的默认配置）
      logic-delete-value: 1
      # 逻辑未删除全局值（0表示未删除，这也是Mybatis Plus的默认配置）
      logic-not-delete-value: 0
  configuration:
    mapUnderscoreToCamelCase: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl

common:
  jwt:
    valid:
      seconds: 7200

#blade:
#  redis:
#    serializerType: json